import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DevRoleSwitcher } from "../components/roleSwitcher/page";
import AuthProvider from "../components/providers/AuthProvider";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GiftFlow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      
      <body className="min-h-full flex flex-col">
        <AuthProvider>{children}
          <Toaster
          position="top-center"
          expand={false}
          richColors
          closeButton
          toastOptions={{
            duration: 4000,
            className: "font-sans text-xs font-semibold rounded-xl shadow-lg border",
          }}
        />
        </AuthProvider>
      </body>
    </html>
  );
}
