import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import AuthProvider from "../components/providers/AuthProvider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "GiftFlow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable} ${GeistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          {children}
          <Toaster
            position="top-center"
            expand={false}
            richColors
            closeButton
            toastOptions={{
              duration: 4000,
              className: "font-sans text-xs font-semibold rounded-xl shadow-lg border",
            }}
          />
        </AuthProvider>
      </body>
    </html>
  );
}